import Head from 'next/head'
import { Text, VStack } from '@chakra-ui/react'
import useConnection from '@hooks/useConnection'
import React, { useEffect } from 'react'
export default function Home() {
  const connection = useConnection()

  useEffect(() => {
    connection.connect();
  }, [connection.address])
  return (
    <>
      <Head>
        <title>YUZBIR / Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <VStack>
        <Text textStyle={'mainPage'} fontSize={'2xl'}>
          Welcome to 101
        </Text>
      </VStack>
    </>
  )
}
