import React from 'react'
import NftCard from '@components/Market/NftCard'
import { Flex, SimpleGrid } from '@chakra-ui/react'
import Head from 'next/head'
const Market = () => {
  return (
    <>
      <Head>
        <title>YUZBIR / Market</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex h={'100%'}>
        <SimpleGrid columns={{ base: 1, md: 5 }} spacing={5} p={2}>
          <NftCard />
          <NftCard />
          <NftCard />
          <NftCard />
          <NftCard />
          <NftCard />
        </SimpleGrid>
      </Flex>
    </>
  )
}

export default Market
