import React from 'react'
import NftCard from '@components/Market/NftCard'
import {
  Flex,
  SimpleGrid,
  Input,
  VStack,
  InputGroup,
  InputRightElement,
  useColorModeValue,
} from '@chakra-ui/react'
import Head from 'next/head'
import { BsSearch } from 'react-icons/bs'
export const Market = () => {
  return (
    <VStack>
      <Head>
        <title>YUZBIR / Market</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex w={'100%'} justifyContent={'center'} gap={'20px'}>
        <InputGroup
          w={'350px'}
          bg={useColorModeValue('light.200', 'transparent')}
          rounded={'10px'}
        >
          <Input placeholder="Enter address and nft search" />
          <InputRightElement
            bg={'transparent'}
            border={'none'}
            cursor={'pointer'}
            _hover={{ opacity: 0.5 }}
            children={<BsSearch color={'gray'} />}
          />
        </InputGroup>
        <InputGroup
          w={'350px'}
          rounded={'10px'}
          bg={useColorModeValue('light.200', 'transparent')}
        >
          <Input placeholder="Enter name and nft search" w={'350px'} />
          <InputRightElement
            bg={'transparent'}
            border={'none'}
            cursor={'pointer'}
            _hover={{ opacity: 0.5 }}
            children={<BsSearch color={'gray'} />}
          />
        </InputGroup>
      </Flex>
      <Flex h={'100%'}>
        <SimpleGrid columns={{ base: 1, md: 5 }} spacing={5} p={2}>
          <NftCard />
        </SimpleGrid>
      </Flex>
    </VStack>
  )
}

export default Market
