import React from 'react'
import Head from 'next/head'
export const Settings = () => {
  return (
    <>
      <Head>
        <title>YUZBIR / Settings</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Settings</div>
    </>
  )
}

export default Settings
